import ClientOnly from '@/components/ClientOnly'
import Loading from '@/components/Loading'
import AppHeader from '@/components/app-header/AppHeader'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='jp'>
      <body>
        <ClientOnly>
          <Loading />
          <div className='sticky top-0'>
            <AppHeader />
          </div>
          {children}
        </ClientOnly>
      </body>
    </html>
  )
}
