import AppHeader from '@/components/app-header/AppHeader'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className='sticky top-0'>
        <AppHeader disableMenu />
      </div>
      {children}
    </>
  )
}
