import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { LoadingProvider } from './contexts/LoadingProvider'
import { AxiosProvider } from './contexts/AxiosProvider'
import { AuthProvider } from './contexts/AuthContext'
import { EnvProvider } from './contexts/EnvContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='jp'>
      <body className={inter.className}>
        <LoadingProvider>
          <EnvProvider>
            <AxiosProvider>
              <AuthProvider>{children}</AuthProvider>
            </AxiosProvider>
          </EnvProvider>
        </LoadingProvider>
      </body>
    </html>
  )
}
