import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { LoadingProvider } from './contexts/LoadingContext'
import { AxiosProvider } from './contexts/AxiosContext'
import { AuthProvider } from './contexts/AuthContext'
import { EnvProvider } from './contexts/EnvContext'
import { DrawerProvider } from './contexts/DrawerContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='jp'>
      <head>
        <link rel='manifest' href='/manifest.json' />
        <link rel='apple-touch-icon' href='/icons/icon.png' />
        <meta name='theme-color' content='#2B3440' />
      </head>
      <body className={inter.className}>
        <LoadingProvider>
          <DrawerProvider>
            <EnvProvider>
              <AxiosProvider>
                <AuthProvider>{children}</AuthProvider>
              </AxiosProvider>
            </EnvProvider>
          </DrawerProvider>
        </LoadingProvider>
      </body>
    </html>
  )
}
