import ClientOnly from '@/components/ClientOnly'
import Loading from '@/components/Loading'
import AppHeaderCompany from '@/components/app-header-company/AppHeaderCompany'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <ClientOnly>
      <Loading />
      <div className='sticky top-0'>
        <AppHeaderCompany />
      </div>
      {children}
    </ClientOnly>
  )
}
